services:
  dnsmasq:
    build: 
      context: ./dnsmasq
      network: host
      args:
        PXE_SERVER_IP: ${PXE_SERVER_IP}
    container_name: pxe-dnsmasq
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq/tftp:/tftpboot

  http:
    build:
      context: ./nginx
      network: host
      args:
        PXE_SERVER_IP: ${PXE_SERVER_IP}
    container_name: pxe-nginx
    network_mode: host
    volumes:
      - ./nginx/www:/var/www/localhost/htdocs
