services:
  http:
    volumes:
      - "${EXPORT_RO}:/var/www/htdocs/media:ro"
      - ./nginx/runtime-start.sh:/rpi3b-pxe-start.sh:ro
      - ./nginx/runtime-nginx.conf:/rpi3b-pxe-nginx.conf:ro
    command: ["/rpi3b-pxe-start.sh"]

  samba:
    volumes:
      - "${SAMBA_ROOT}:/shared"
